service:
  name: image harmony
  port: 5000
  tags: 
    - interface:gRPC
    - support:hikvision
    - support:local image
    - support:opencv video reader(cpu)
    - support:opencv video reader(gpu)

consul:
  ip: 10.10.10.2
  port: 8500

settings:
  historyMaxSize: 100
  imageLoaderTimeout: 120