services:
  - name: image harmony gRPC
    type: gRPC
    port: 8080
    tags: 
      - interface:gRPC
      - support:hikvision
      - support:local image
      - support:opencv video reader(cpu)
      - support:opencv video reader(gpu)
  - name: image harmony HTTP
    type: HTTP
    port: 5000
    tags:
      - interface:REST
      - support:hikvision
      - support:local image
      - support:opencv video reader(cpu)
      - support:opencv video reader(gpu)

consul:
  ip: 10.10.10.2
  port: 8500

settings:
  historyMaxSize: 100
  imageLoaderTimeout: 120