service:
  name: image harmony
  port: 5000
  tags: 
    - interface:gRPC
    - support:hikvision
    - support:local image

consul:
  ip: 10.0.0.2
  port: 8500

settings:
  historyMaxSize: 100
  imageLoaderTimeout: 120